chore: rename repository

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -83,20 +83,20 @@ jobs:
           echo "Workflow run ID: ${{ steps.trigger_and_wait.outputs.id }}"
           echo "Workflow URL: ${{ steps.trigger_and_wait.outputs.html_url }}"
 
-      - name: Checkout AccelBrain-dev__confidential repository
+      - name: Checkout AccelBrain repository
         if: steps.trigger_and_wait.outputs.conclusion == 'success'
         uses: actions/checkout@v4
         with:
-          repository: InnoIPA/AccelBrain-dev__confidential
+          repository: InnoIPA/AccelBrain
           ref: dev
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          path: accelbrain-confidential
+          path: accelbrain
 
-      - name: Get latest release tag from accelbrain-confidential repo
+      - name: Get latest release tag from accelbrain repo
         if: steps.trigger_and_wait.outputs.conclusion == 'success'
         id: get_release
         run: |
-          cd accelbrain-confidential || (echo "Directory not found" && exit 1)
+          cd accelbrain || (echo "Directory not found" && exit 1)
           git fetch --tags
           TAG=$(git tag --sort=-v:refname | head -n 1)
           echo "release_tag=$TAG" >> $GITHUB_OUTPUT
@@ -105,12 +105,12 @@ jobs:
       - name: Update docker-compose.yml image tag
         if: steps.trigger_and_wait.outputs.conclusion == 'success'
         run: |
-          cd accelbrain-confidential || (echo "Directory not found" && exit 1)
+          cd accelbrain || (echo "Directory not found" && exit 1)
           sed -i "s|innodiskorg/ollama:.*|innodiskorg/ollama:v${{ steps.get_version.outputs.version }}|g" docker-compose.yml
 
       - name: Update CHANGELOG.md
         run: |
-          cd accelbrain-confidential || (echo "Directory not found" && exit 1)
+          cd accelbrain || (echo "Directory not found" && exit 1)
           echo "Reading current version from CHANGELOG.md"
 
           # 先取出上一個版本號（第一個 [vX.X]）
@@ -196,4 +196,4 @@ jobs:
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
           commit_message: "chore: bump model server image to v${{ steps.get_version.outputs.version }}"
-          repository: ./accelbrain-confidential
+          repository: ./accelbrain
